# Colors (Iceberg Light)
colors:
  # Default colors
  primary:
    background: '#e8e9ec'
    foreground: '#33374c'

  # Normal colors
  normal:
    black:   '#dcdfe7'
    red:     '#cc517a'
    green:   '#668e3d'
    yellow:  '#c57339'
    blue:    '#2d539e'
    magenta: '#7759b4'
    cyan:    '#3f83a6'
    white:   '#33374c'

  # Bright colors
  bright:
    black:   '#8389a3'
    red:     '#cc3768'
    green:   '#598030'
    yellow:  '#b6662d'
    blue:    '#22478e'
    magenta: '#6845ad'
    cyan:    '#327698'
    white:   '#262a3f'
